# Generated by Django 4.1.4 on 2022-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='week',
            name='weeknumber',
            field=models.IntegerField(unique=True),
        ),
    ]
