# Generated by Django 4.1.4 on 2023-02-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_productgroup'),
        ('era', '0002_meal_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.AddField(
            model_name='meal',
            name='product',
            field=models.ManyToManyField(to='nutrition.product'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('diner', 'Diner'), ('snack', 'Snack')], max_length=10),
        ),
    ]
