# Generated by Django 4.1.4 on 2022-12-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0002_day_alter_week_weeknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.day'),
            preserve_default=False,
        ),
    ]
