# Generated by Django 4.1.4 on 2022-12-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0003_week_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.week'),
            preserve_default=False,
        ),
    ]
