# Generated by Django 4.1.4 on 2023-01-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0004_remove_week_day_day_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='friday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='monday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='saturday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='sunday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='thursday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='tuesday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='wednesday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
