# Generated by Django 4.1.4 on 2023-01-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0005_remove_day_day_day_friday_day_monday_day_saturday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='weeknumber',
            new_name='week',
        ),
        migrations.AddField(
            model_name='week',
            name='friday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='monday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='saturday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='sunday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='thursday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='wednesday',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
