# Generated by Django 4.1.4 on 2023-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0007_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10)),
            ],
        ),
    ]
