# Generated by Django 4.1.4 on 2023-01-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0008_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.week'),
            preserve_default=False,
        ),
    ]
