# Generated by Django 4.1.4 on 2023-01-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0010_remove_day_name_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=1, null=True),
        ),
    ]
