# Generated by Django 4.1.4 on 2023-01-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0012_alter_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='wednesday',
        ),
    ]
