# Generated by Django 4.1.4 on 2023-01-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0013_remove_week_friday_remove_week_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='week',
        ),
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.day'),
            preserve_default=False,
        ),
    ]
