# Generated by Django 4.1.4 on 2023-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0014_remove_meal_week_meal_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(to='era.meal'),
        ),
    ]
