# Generated by Django 4.1.4 on 2023-01-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0015_remove_meal_day_day_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.day'),
            preserve_default=False,
        ),
    ]
