# Generated by Django 4.1.4 on 2023-01-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0016_remove_day_meals_meal_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.week'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
