# Generated by Django 4.1.5 on 2023-01-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0017_meal_week_alter_meal_day_alter_week_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.PositiveIntegerField(),
        ),
    ]
