# Generated by Django 4.1.4 on 2023-02-03 20:13

from django.db import migrations, models
import django.db.models.deletion
import era.models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0018_alter_week_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.meal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.PositiveIntegerField(default=era.models.Week.get_last_week),
        ),
    ]
