# Generated by Django 4.1.4 on 2023-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0019_remove_meal_day_day_meal_alter_week_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='week',
        ),
        migrations.AddField(
            model_name='week',
            name='monday',
            field=models.ManyToManyField(to='era.meal'),
        ),
    ]
