# Generated by Django 4.1.4 on 2023-02-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0020_remove_meal_week_week_monday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='monday',
        ),
    ]
