# Generated by Django 4.1.4 on 2023-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0021_remove_week_monday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meal',
        ),
        migrations.AddField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(to='era.meal'),
        ),
    ]
