# Generated by Django 4.1.4 on 2023-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_product_unit'),
        ('era', '0023_day_meal_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meal_1',
        ),
        migrations.AddField(
            model_name='day',
            name='meal_1',
            field=models.ManyToManyField(to='nutrition.product'),
        ),
    ]
