# Generated by Django 4.1.4 on 2023-02-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0024_remove_day_meal_1_day_meal_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meals',
        ),
    ]
