# Generated by Django 4.1.4 on 2023-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0025_remove_day_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='monday',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='tuesday',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
