# Generated by Django 4.1.4 on 2023-02-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0026_week_monday_week_tuesday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='meal_1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='week',
            name='tuesday',
        ),
    ]
