# Generated by Django 4.1.4 on 2023-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0028_day_meal_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='meal_1',
            field=models.ManyToManyField(to='era.meal'),
        ),
    ]
